import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Suroi Autogenerated Wiki",
  description:
    "Unofficial wiki for Suroi.io. Autogenerated statistics and more.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen bg-background font-sans antialiased box-border dark ${inter.className}`}
      >
        {children}
      </body>
    </html>
  );
}
