import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/react";
import TanstackQuery from "@/components/providers/TanstackQuery";

const font = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "Suroi Auto Wiki",
    template: "%s | Suroi Auto Wiki",
  },
  description: "Unofficial wiki for Suroi.io. Autogenerated stats and more.",
};

export const viewport: Viewport = {
  themeColor: "#202020",
  colorScheme: "dark",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen bg-background font-sans antialiased text-white box-border dark ${font.className}`}
      >
        <TanstackQuery>{children}</TanstackQuery>
        <Analytics />
      </body>
    </html>
  );
}
