<Stub />

# Background

Radios are a type of communication device that utilizes electromagnetic radio waves between three hertz to 300 gigahertz. These waves are generated by a transmitter with an antenna, which radiates the radio waves. The first radio communication systems were developed in 1895 by Guglielmo Marconi and used morse code.

# Strategies

## Using

- The radio's only function is to summon an [Airdrop](/obstacles/airdrop_crate) at the location where it is fired.
- It deals no damage and cannot be used as a [Weapon](/weapons).

# Obtaining

- Radios can be found rarely from common loot sources.

## Trivia

- The radio uses the same sound effects as the [Deathray](/weapons/guns/deathray) except for the firing sound

# History

- v0.14.0
  - Range increased to 50 (from 0)
  - Bullet speed decreased to 0.01 (from 1)
- v0.13.0
  - Added

# Gallery

<Gallery
  images={[
    {
      url: "/img/articles/weapons/guns/radio/radio_ground.png",
      author: "1092384",
      caption: "A player finding a Radio on the ground in v0.14.0",
    },
  ]}
/>
